#!/usr/bin/env python3
"""Build a ready-to-compile Arduino sketch folder for one board.

  prepare_arduino.py --target esp32s3 --out /tmp/mcufit_bench
  prepare_arduino.py --target rp2040 --models person_detect,ad --out /tmp/mcufit_bench

Copies the portable sketch plus only the model arrays you asked for, so a board
with little flash can still run part of the benchmark. The model arrays are
about 1.1 MB of C each, which is why they are not duplicated in the repo.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SKETCH_DIR = REPO / "arduino" / "mcufit_bench_portable"
MODEL_SRC_DIR = REPO / "arduino" / "mcufit_bench_nano"

# Which TFLM Arduino library a board needs. The header has to be named in a
# plain include for arduino-cli to resolve it to an installed library, so the
# choice is made here and written into model_list.h.
LIBRARIES = {
    "chirale": ("Chirale_TensorFlowLite.h", "Chirale_TensorFlowLite"),
    "tflm_esp32": ("tflm_esp32.h", "tflm_esp32"),
    "tensorflowlite_esp32": ("TensorFlowLite_ESP32.h", "TensorFlowLite_ESP32"),
    "tensorflowlite": ("TensorFlowLite.h", "Arduino_TensorFlowLite"),
}

# symbol -> the name the model is reported under, which is its upstream name.
MODELS = {
    "person_detect": "person_detect.tflite",
    "kws": "kws_ref_model.tflite",
    "ic_resnet": "pretrainedResnet_quant.tflite",
    "ad": "ad01_int8.tflite",
}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--target", required=True,
                    help="short id for this board, e.g. esp32s3, rp2040, teensy41. "
                         "Becomes the 'target' field in every record.")
    ap.add_argument("--models", default=",".join(MODELS),
                    help=f"comma-separated, from: {', '.join(MODELS)}. Default is all four.")
    ap.add_argument("--library", choices=sorted(LIBRARIES), default=None,
                    help="TFLM Arduino library to include. Defaults to tflm_esp32 for "
                         "an esp target, chirale otherwise.")
    ap.add_argument("--out", required=True, type=Path,
                    help="output sketch folder. Its name is what arduino-cli compiles.")
    args = ap.parse_args()

    wanted = [m.strip() for m in args.models.split(",") if m.strip()]
    unknown = [m for m in wanted if m not in MODELS]
    if unknown:
        print(f"unknown model(s): {', '.join(unknown)}", file=sys.stderr)
        print(f"pick from: {', '.join(MODELS)}", file=sys.stderr)
        return 2

    library = args.library or ("tflm_esp32" if args.target.lower().startswith("esp")
                               else "chirale")
    header, lib_name = LIBRARIES[library]

    # arduino-cli requires the .ino basename to match the folder name.
    out = args.out.expanduser().resolve()
    out.mkdir(parents=True, exist_ok=True)
    shutil.copy(SKETCH_DIR / "mcufit_bench_portable.ino", out / f"{out.name}.ino")
    shutil.copy(MODEL_SRC_DIR / "model_data.h", out / "model_data.h")

    total = 0
    for sym in wanted:
        src = MODEL_SRC_DIR / f"model_{sym}.cpp"
        if not src.exists():
            print(f"missing {src}, run the regeneration command in the README", file=sys.stderr)
            return 1
        shutil.copy(src, out / f"model_{sym}.cpp")
        total += src.stat().st_size

    entries = ",\\\n".join(
        f'    {{"{MODELS[s]}", g_{s}, g_{s}_len, g_{s}_sha256}}' for s in wanted
    )
    (out / "model_list.h").write_text(
        "// Generated by scripts/prepare_arduino.py. Do not edit.\n"
        "#pragma once\n\n"
        f"#include <{header}>\n"
        f'#define MCUFIT_TFLM_LIB "{lib_name}"\n\n'
        f'#define MCUFIT_TARGET "{args.target}"\n\n'
        "#define MCUFIT_MODEL_LIST {\\\n" + entries + "\\\n}\n"
    )

    print(f"sketch ready: {out}")
    print(f"  target  {args.target}")
    print(f"  library {lib_name}  (install it first: arduino-cli lib install \"{lib_name}\")")
    print(f"  models  {', '.join(wanted)}  ({total / 1e6:.1f} MB of C arrays)")
    print()
    print("next, with your board's FQBN:")
    print(f"  arduino-cli compile --fqbn <FQBN> {out}")
    print(f"  arduino-cli upload -p <PORT> --fqbn <FQBN> {out}")
    print()
    print("if it will not fit, drop models or lower the arena:")
    print(f"  prepare_arduino.py --target {args.target} --models person_detect --out {out}")
    print("  arduino-cli compile --build-property "
          "compiler.cpp.extra_flags=-DMCUFIT_ARENA_KB=64 ...")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
